---
title: "Predicting Soccer Match Outcomes"
author: "Theyab Alkhoori, Jasmine Moskowitz"
date: "2025-12-02"
output: html_document
---

# Introduction
Around the world, soccer is a popular sport. Millions of people enjoy using each team's data to predict match outcomes. Our project aims to predict match results of the 2017 season. We will predict the 2017 season using the statistics from the 2008 to 2016 seasons, then compare our predictions with the actual outcomes. In the end we hope to know if the home team wins, ties, or loses and well as the number of goals scored during the game. Once complete we can then compare our results with the actual results of the game.

# References 
We plan to execute our desired tasks by using the **European Soccer Database** from Kaggle (https://www.kaggle.com/datasets/hugomathien/soccer/data). This source includes information from more than 25,000 games, more than 10,000 players, and eleven European nations. The data contains match statistics, results, and other information all contained in csv files. 
We will split the data into two parts: train and test. The training data will contain data from the season 2008 to 2016. The test data will contain data from the 2017 season. 

# Methods
## Task 1: Data Preparation
Our first task is to clean out the data from the csv files. We want to extract all the necessary data to make it easier to complete our tasks. 

## Task 2: Classification
Our second task is using classification methods to predict match outcomes (home win, tie, home loss)

## Task 3: Regression
Our third task is to predict the number of goals scored in a match. 

