---
title: "Predicting AirBnB Rental Prices"
author: "Group 11: Trevor Isaacson, Jonathan Olavarria, Jasmine DeMeyer"
date: "12/10/2021"
output: beamer_presentation #:
    #theme: "Frankfurt"
    #colortheme: "orchid"
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = FALSE)
set.seed(445)
knitr::opts_chunk$set(message = FALSE)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(e1071)
library(rmarkdown)
library(glmnet)
library(knitr)
library(leaps)
library(tree)
library(dplyr)
library(caret)
library(gbm)
library(randomForest)
library(GGally)
library(pls)
library(splines)
library(boot)
```

# Motivation

- You are looking for some additional income and decide renting on AirBnB is the best option
- How much should you rent your extra space for?


# Data

- In general, AirBnB data is very open and be easily accessed
- The original dataset is from a past Kaggle competition 
  - Contained over 74,000 individual listings
- For sake of time and processing power, we took a random sample of 17,500 from those 74,000 listings
- They also provided a testing file
- Since the competition is over, we will compile our final predictions on that file using our best model 

# Data

- Consists of 30 variables
- Variables are about the property, property location, the host and host reviews 
- After cleaning and eliminating variables, our data consisted of 22 variables
- 


# Questions?




## References

